FROM node:20-alpine AS builder

WORKDIR /app/backend

COPY backend/package*.json ./
RUN npm install

COPY backend/ ./

RUN npm run build

# --- Production stage ---
FROM node:20-alpine

WORKDIR /app/backend

ENV NODE_ENV=production

COPY --from=builder /app/backend/dist ./dist
COPY --from=builder /app/backend/node_modules ./node_modules

EXPOSE 8003

CMD ["node", "dist/book.js"]
